# Generated by Django 5.0.2 on 2024-03-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bodey',
            new_name='body',
        ),
    ]
